# Generated by Django 4.1.2 on 2022-10-27 02:05

import cmm.models.base.unique_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mst', '0001_initial'),
        ('cmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dkido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='version')),
                ('create_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='create time')),
                ('creator', models.CharField(blank=True, editable=False, max_length=120, null=True, verbose_name='creator')),
                ('update_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='update time')),
                ('updater', models.CharField(blank=True, editable=False, max_length=120, null=True, verbose_name='updater')),
                ('valid_flag', models.BooleanField(default=True, verbose_name='valid')),
                ('cshainno', models.CharField(max_length=32, verbose_name='職員番号')),
                ('dhtreingb_dte', models.DateField(blank=True, null=True, verbose_name='発令年月日')),
                ('nnmn_ido_cde', models.CharField(blank=True, max_length=80, null=True)),
                ('nnmn_ido_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('znsyk_kojin_cde', models.CharField(blank=True, max_length=8, null=True, verbose_name='前職指定個人番号')),
                ('cnamekna', models.CharField(blank=True, max_length=40, null=True, verbose_name='カナ氏名')),
                ('cnameknj', models.CharField(blank=True, max_length=40, null=True, verbose_name='漢字氏名')),
                ('seibetu_nme', models.CharField(blank=True, max_length=2, null=True)),
                ('dbirth_dte', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('dsaiyo_dte', models.DateField(blank=True, null=True, verbose_name='採用年月日')),
                ('kkn_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('szk_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('yosan_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('knmei_nme', models.CharField(blank=True, max_length=40, null=True)),
                ('syksy_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('kinmsaki_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('nnki_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('nnki_mr_dte', models.DateField(blank=True, null=True)),
                ('dnnki_mr_dte', models.CharField(blank=True, max_length=7, null=True, verbose_name='任期満了年月日')),
                ('tsykgo_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('hkyh_nme', models.CharField(blank=True, max_length=40, null=True)),
                ('kyu', models.IntegerField(blank=True, null=True)),
                ('kyu_ido_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('goho', models.IntegerField(blank=True, null=True)),
                ('goho_ido_nme', models.CharField(blank=True, max_length=80, null=True)),
                ('nxt_syky_dte', models.CharField(blank=True, max_length=5, null=True, verbose_name='次期昇給期')),
                ('goho_ido_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '017'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goho_ido', to='cmm.code', verbose_name='号俸異動種目')),
                ('hkyh_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '053'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hokyuhyo', to='cmm.code', verbose_name='俸給表')),
                ('ido_syumoku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mst.idosyumoku', verbose_name='異動種目')),
                ('kei_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '005'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kei', to='cmm.code', verbose_name='系')),
                ('kinmsaki_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '012'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kinmusaki', to='cmm.code', verbose_name='採用直前の勤務先')),
                ('kkn_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '003'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kikan', to='cmm.code', verbose_name='機関')),
                ('knmei_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '008'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kanmei', to='cmm.code', verbose_name='官名')),
                ('kyu_ido_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '016'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyu_ido', to='cmm.code', verbose_name='級異動種目')),
                ('nnki_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '116'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ninki', to='cmm.code', verbose_name='任期区分')),
                ('seibetu_kbn', models.ForeignKey(blank=True, limit_choices_to={'category__category': '047'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seibetu', to='cmm.code', verbose_name='性別')),
                ('syksy_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '052'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='syokusyu', to='cmm.code', verbose_name='職種')),
                ('szk_cde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shozoku', to='cmm.organization', verbose_name='所属')),
                ('tsykgo_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '052'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='syusyokusaki', to='cmm.code', verbose_name='退職等後の就職先等コード')),
                ('yosan_cde', models.ForeignKey(blank=True, limit_choices_to={'category__category': '007'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='yosanko', to='cmm.code', verbose_name='予算項')),
            ],
            options={
                'db_table': 'dkido',
                'managed': True,
            },
            bases=(cmm.models.base.unique_mixin.UniqueConstraintMixin, models.Model),
        ),
    ]
