# Generated by Django 4.1.2 on 2022-11-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mst', '0001_initial'),
        ('jinji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkido',
            name='ido_syumoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mst.idosyumoku', verbose_name='異動種目'),
        ),
    ]
