# Generated by Django 4.1.2 on 2022-11-02 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvlog',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='create time'),
        ),
    ]
