# Generated by Django 4.1.2 on 2022-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmm', '0002_alter_csvlog_create_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='cmm_person_unique',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='cmm_person_unique'),
        ),
    ]
